// Generated by CoffeeScript 1.9.3
(function() {
  var i, len, method_count, module, name, njs_util, ref, route, routes, rpr, value;

  njs_util = require('util');

  rpr = njs_util.inspect;

  this.LODASH = require('lodash');

  this.TSORT = require('./TSORT');

  this.BLOOM = require('./BLOOM');

  this.columnify = require('columnify');

  this.INTERSKIPLIST = require('./INTERSKIPLIST');

  method_count = 0;

  routes = ['./TRM', './BITSNPIECES', './TYPES', './SHIM', './XJSON'];

  for (i = 0, len = routes.length; i < len; i++) {
    route = routes[i];
    ref = module = require(route);
    for (name in ref) {
      value = ref[name];
      if (this[name] != null) {
        throw new Error("duplicate name " + (rpr(name)));
      }
      method_count += +1;
      if ((Object.prototype.toString.call(value)) === '[object Function]') {
        value = value.bind(module);
      }
      this[name] = value;
    }
  }

}).call(this);
