// Generated by CoffeeScript 1.8.0
(function() {
  var method_count, module, name, njs_util, route, routes, rpr, value, _i, _len, _ref;

  njs_util = require('util');

  rpr = njs_util.inspect;

  method_count = 0;

  routes = ['./TRM', './BITSNPIECES', './TYPES'];

  for (_i = 0, _len = routes.length; _i < _len; _i++) {
    route = routes[_i];
    _ref = module = require(route);
    for (name in _ref) {
      value = _ref[name];
      if (this[name] != null) {
        throw new Error("duplicate name " + (rpr(name)));
      }
      method_count += +1;
      if ((Object.prototype.toString.call(value)) === '[object Function]') {
        value = value.bind(module);
      }
      this[name] = value;
    }
  }

  if (module.parent == null) {
    console.log("acquired " + method_count + " names from " + routes.length + " sub-modules");
    this.dir(this);
  }

}).call(this);
