// Generated by CoffeeScript 2.0.0-beta3
(function() {
  var base, i, len, method_count, module, name, njs_util, ref, route, routes, rpr, value, σ_cnd;

  njs_util = require('util');

  rpr = njs_util.inspect;

  σ_cnd = Symbol.for('cnd');

  if (global[σ_cnd] == null) {
    global[σ_cnd] = {};
  }

  if ((base = global[σ_cnd]).t0 == null) {
    base.t0 = Date.now();
  }

  method_count = 0;

  routes = ['./TRM', './BITSNPIECES', './TYPES'];

  for (i = 0, len = routes.length; i < len; i++) {
    route = routes[i];
    ref = module = require(route);
    for (name in ref) {
      value = ref[name];
      if (this[name] != null) {
        throw new Error(`duplicate name ${rpr(name)}`);
      }
      method_count += +1;
      if ((Object.prototype.toString.call(value)) === '[object Function]') {
        value = value.bind(module);
      }
      this[name] = value;
    }
  }

  this.XJSON = require('./XJSON');

  this.suspend = require('./suspend');

}).call(this);

//# sourceMappingURL=main.js.map
