// Generated by CoffeeScript 1.9.3
(function() {
  var slice = [].slice;

  this.shim = function() {
    var keys;
    keys = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    if (keys.length > 0) {
      throw new Error("keys not yet implemented; use `shim()` instead");
    }
    return require('es6-shim');
  };

}).call(this);
